baseURL: "https://FatimaEzzahra-ELFAKIR06.github.io/portfolio/"
languageCode: "en-us"
title: "Fatima Ezzahra's Portfolio"
#theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

params:
  title: "Hugo Profile"
  description: "Text about my cool site"
  favicon: "/fav.png"

  useBootstrapCDN: false
  mathjax: false
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left

  navbar:
    align: ms-auto
    brandName: "Hugo Profile"
    disableSearch: false
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero Section
  hero:
    enable: true
    intro: "Hey dear, my name is"
    title: "Fatima Ezzahraa ELFAKIR ."
    subtitle: "Building solutions for people is what I do, driven by my passion for programming, also I'm passionate about Astronomy."
    content: "Just as the stars align in perfect harmony, I bring design and functionality together to create seamless web experiences."
    image: "/images/hero.svg"
    bottomImage:
      enable: true
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: "fab fa-github"
          url: "https://github.com/"
        - icon: "fab fa-instagram"
          url: "https://www.instagram.com/elfr.fatimaezzahraa/"
      customIcons:
        - icon: "/fav.png"
          url: "https://www.instagram.com/elfr.fatimaezzahraa/"

  # About Me Section
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I’m a student of Applied Computer Science with a love for astronomy, music, and art. I enjoy exploring how technology can blend with creativity to solve problems and inspire others.
      As I said, I also have a great appreciation for music and art, which often inspire my approach to technology and design.

      Currently, I’m dreaming up a project that combines my passion for the cosmos and coding: a tool to help people track stars, planets, and celestial events. My goal is to make the wonders of the universe more accessible and engaging for everyone.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "PYTHON"
        - "Onshape"
        - "Something else"
        - "So on..."

  # Experience Section
  experience:
    enable: true
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "Worked on high-scale applications, improving user experience and performance."

      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: "Developed backend services for e-commerce applications."

      - job: "UI/UX Designer"
        company: "Netflix"
        companyUrl: "https://example.com"
        date: "June 2017 - Nov 2019"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: "Designed intuitive user interfaces for streaming applications."

  # Achievements Section
  achievements:
    enable: true
    items:
      - title: "Project"
        content: "I solved all problems with an optimal solution."
        url: "https://example.com"
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLcXjq_HUwzKEKtgBZj5Yet4AYWvuuFdRePA&s"

  # Projects Section
  projects:
    enable: true
    items:
      - title: "Cars Management"
        content: "A smart and efficient car management system built with Python, designed to track, organize, and optimize vehicle data seamlessly."
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLcXjq_HUwzKEKtgBZj5Yet4AYWvuuFoc"
        featured:
          name: "Demo"
          link: "https://hugo-profile.netlify.app"
        badges:
          - "Hugo"
          - "Python"
        links:
          - icon: "fa fa-envelope"
            url: "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo"

  # Contact Section
  contact:
    enable: true
    content: "My inbox is always open, like a cosmic gateway, whether you have a question, a wild idea, or just want to say hi!"
    btnName: "Mail me"
    btnLink: "mailto:fatymaezzahraaelfakir@gmail.com"
    formspree:
      enable: true
      formId: "abcdefgh"
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5

  # Footer Section
  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: "Recent Posts"
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: "https://github.com/"
      linkedin: "www.linkedin.com/in/fatima-ezzahraa-elfakir-88bb5a320"
      twitter: "https://twitter.com"
      instagram: "https://www.instagram.com/elfr.fatimaezzahraa/"
      facebook: "https://facebook.com"

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

